### ISSUE TITLE
modul "plugin.appodeal" not found

### ISSUE THREAD

**Issue by arkadi** [agramonte/com.cabagomez#3]
i have using your plugin. i cloned your repository in my folder /Users/yourname/Solar2DPlugins/.

in build.settings i have code
`plugins ={
		["plugin_ironsource"] =
		{
				publisherId = "com.cabagomez"
		}
	},`

and in lua code i have code 
`local appodeal = require( "plugin.appodeal" );`

but i have error  "modul "plugin.appodeal" not found"

**Comment by agramonte** [comment]
It doesn’t work in the simulator. You should check for the simulator and wrap the statements. It will only work on a real device.

**Comment by arkadi** [comment]
i tested in real iOS device

**Comment by agramonte** [comment]
oh. I see your problem. You are using the Ironsource plugin but are referencing the appodeal plugin.

If you want to use appodeal:
plugins ={ ["plugin.appodeal"] = { publisherId = "com.cabagomez" } },

and
local appodeal = require( "plugin.appodeal" );

If you want to use ironsource:
plugins ={ ["plugin_ironsource"] = { publisherId = "com.cabagomez" } },

and
local ironsource = require( "plugin.ironsource" )
